language: ruby
sudo: false

script: bundle exec rake

after_success:
  - bundle exec codeclimate-test-reporter

matrix:
  include:
    - rvm: 2.4.2
      gemfile: gemfiles/activerecord_4.gemfile
      env: ADAPTER=active_record
    - rvm: 2.3.5
      gemfile: gemfiles/activerecord_4.gemfile
      env: ADAPTER=active_record
    - rvm: 2.2.8
      gemfile: gemfiles/activerecord_4.gemfile
      env: ADAPTER=active_record

    - rvm: 2.4.2
      gemfile: gemfiles/activerecord_5.gemfile
      env: ADAPTER=active_record
    - rvm: 2.3.5
      gemfile: gemfiles/activerecord_5.gemfile
      env: ADAPTER=active_record
    - rvm: 2.2.8
      gemfile: gemfiles/activerecord_5.gemfile
      env: ADAPTER=active_record

    - rvm: 2.4.2
      gemfile: gemfiles/mongoid_4.gemfile
      env: ADAPTER=mongoid
    - rvm: 2.3.5
      gemfile: gemfiles/mongoid_4.gemfile
      env: ADAPTER=mongoid
    - rvm: 2.2.8
      gemfile: gemfiles/mongoid_4.gemfile
      env: ADAPTER=mongoid

    - rvm: 2.4.2
      gemfile: gemfiles/mongoid_5.gemfile
      env: ADAPTER=mongoid
    - rvm: 2.3.5
      gemfile: gemfiles/mongoid_5.gemfile
      env: ADAPTER=mongoid
    - rvm: 2.2.8
      gemfile: gemfiles/mongoid_5.gemfile
      env: ADAPTER=mongoid


services: mongodb

addons:
  code_climate:
    repo_token: 6bd8d374b120a5449b9a4b7dfda40cc0609dbade48a1b6655f04a9bc8de3a3ee
